### ISSUE TITLE
Change orange icon to custom

### ISSUE THREAD

**Issue by romaromaniv** [JunianNet/WinSparkle.DotNet#2]
![image](https://cloud.githubusercontent.com/assets/28062488/25526027/6bf899dc-2c1a-11e7-9d90-85709b4ec241.png)
How it is possible?
Thanks.

**Comment by junian** [comment]
Hi @romaromaniv ,

Please head to [WinSparkle](https://github.com/vslavik/winsparkle) project and open this issue there.
This project is just wrapper in C#.

Thank you,


Junian

**Comment by romaromaniv** [comment]
Hi Junian.

Please, see answer https://github.com/vslavik/winsparkle/issues/140

I will be happy to donate for the feature in C# wrapper.

Best regards, Roman

**Comment by junian** [comment]
@romaromaniv I'll see what I can do. I also have project using WinSparkle, but so far no problem with current icon.
